### ISSUE TITLE
Enable the use of a dd4hep detector within a processor

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/Framework#1]

**Comment by omar-moreno** [comment]
This requires
1) Loading the compact description of the detector when configuring a set of processors. 
2) Allow access to the in  memory detector by either
   * allowing each processor/producer to call the dd4hep::Detector singleton class themselves 
   * Adding a callback to EventProcessor which provides each processor the top level DetectorElement 

I'm leaning towards option 2 given that most users will want access to the detector elements themselves and not any low level information i.e. envelope volumes.  With option 2, option 1 will still be available for edge cases.

**Comment by tomeichlersmith** [comment]
Not planning to use DD4hep for detector description anymore _and_ this "singleton" style class could easily be implemented from within the condition system.
