### ISSUE TITLE
Re-enable LCIO support

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/Framework#29]
To do this, the following changes will be made: 

- [ ] EventFile will become an interface
- [ ] All existing code in EventFile will move to RootEvenFile 
- [ ] An LcioEventFile will be added to handle LCIO I/O 
- [ ] An EventFile factory will be used to create the required EventFile class at run time.

This should have no impact on how the code is run. 

@bryngemark FYI since you are modifying EventFile for the OverlayProducer.

**Comment by bryngemark** [comment]
Hi @omar-moreno, I'm now at a point where everything works and I'd like to add a special overlay mode functionality (a bool and an if statement 😄  ) to `EventFile::nextEvent()`, which would allow to reset the event counter when we reach the last entry in the the pileup input tree. Do I need to worry about the changes here or can I go ahead and tweak EventFile as is?

**Comment by omar-moreno** [comment]
Yes, EvenFile is now an interface and the current EventFile functionality
has been moved to RootEventFile.

I'm assuming that these changes are going to go into a separate issue? If
so, then make sure to branch off v3.0.0-dev so it's easier to merge in the
changes you need.

**Comment by bryngemark** [comment]
I would like to have this all in the overlay issue, which is close to done. It's based on v2.3

**Comment by omar-moreno** [comment]
OK, that's going to cause issues. As soon as we make the v2.3.0 release,
I'm merging the v3.0.0 changes. That's likely going to completely break
your branch.

If it's possible to break it up, I would do so.

**Comment by bryngemark** [comment]
Sure, event wrapping is a minor detail -- in the overlay code it's just an extra bool in the EventFile initialization. So the EventFile tweak can be pushed after the overlay code is merged with master
