### ISSUE TITLE
Remove dependency on Event

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/Framework#3]
Currently, Framework makes use of a couple of classes defined in the ldmx-sw/Event module.  These include 
* Event/EventDef.h
* Event/RunHeader.h
* Event/EventHeader.h

Some of these can be made generic enough that they can be moved to the Framework module.  However, removing the dependency on the EventBusPassenger is trickier. Whatever the case, for this to compile on it's own, the dependency on these classes will need to be removed.

**Comment by tomeichlersmith** [comment]
I have found a solution to this while working on #9 so I am going to assign myself.
