### ISSUE TITLE
Can't analyze 2 or more different pass names in one run

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/Framework#30]
I discovered this when attempting to analyze several different signal style generators at once.

## Hypothesis
This is being caused by the branch names of the input-file branches being left defined with the previous input-file's pass name (no proof). 

## Solution
I still haven't solved this, but I also wanted to bring this up as something that we may not want to solve.... Are we okay with analyzing more than one different passes in a single run?
- If not, I can implement an exception so that the user knows why they are seeing this error.
- If yes, then I can figure out how to fix this up.

*Not Urgent*: very niche use case of the Framework.

**Comment by tomeichlersmith** [comment]
If we do want to allow this (or not), we probably need to get up to some nonsense here in `EventFile::updateParent`. We use `TTree::CopyAddresses` which looks for branches of the same name. Since the pass name is included in the branch name, we would need to modify this code somehow.

https://github.com/LDMX-Software/Framework/blob/9437e34ba51c810045d3e51fe524a44520f13e86/src/EventFile.cxx#L228-L257

**Comment by bryngemark** [comment]
Just stumbled upon this, sorry that this comment is late but, it is already possible to for instance use a preexisting pass of a collection alongside a collection with the same name but the current pass, in two different instances of a processor, as long as the pass name is specified/specifiable in the processor. I'm almost entirely certain I have done this.

**Comment by tomeichlersmith** [comment]
You are correct that two different pass-names _in parallel_ can be analyzed. This issue pops up when the pass name changes _in sequence_.

For example, I generate some simulated data using the pass name "signal" but then later change the pass name in that config to "eat". This means some of my data files have pass name "signal" while others have pass name "eat" even though they were generated in the same manner. I want to analyze all of these files together (effectively in one process), but when the process closes a "signal" file and opens an "eat" file I get warnings. I have a batch on PR #34 that clears the lookup cache whenever a file is being closed.

https://github.com/LDMX-Software/Framework/blob/b1764baa737311ac53fd1561bea120c23f0dd04d/src/Framework/Event.cxx#L144

This allows the process to continue, but we still get warnings from "CopyAddresses" in update parent.
