### ISSUE TITLE
Update skim rules to enable use of an OR for triggering

### ISSUE THREAD

**Issue by bryngemark** [LDMX-Software/Framework#47]
It would be very nice to be able to have several trigger processors be able to chime in on whether to keep an event. 

My immediate use case is for skims of overlay samples, but this will likely come in handy when we start to do trigger emulation for real. 

The overall plan for the overlay samples is to produce them, store the full deal in Lund, and then run tskims to be stored at (this is the only way to fit a full 1e14 EOT sample at SLAC). Here's what I would like to do for trigger skimming: I want to run a trigger on the no-pileup collections, and one on the with-pileup collections, and keep the event if either of them fire. This is useful for trigger studies (especially, seeing what events we miss out on in a pileup environment) without having to keep all events. (With this scheme one could also consider a random/min bias trigger to keep a few extra events, but not all, for trigger studies. But that's simple enough to code up later.)  

**Proposed solution**
Currently each processor can set a storage hint to keep or drop an event, and in the end, a majority vote is used to decide. But, there is some granularity to the storage hints: `hint_shouldKeep` or `hint_mustKeep`, which are currently not treated differently, as far as I can see: see implementation in `StorageControl.cxx` [here](https://github.com/LDMX-Software/Framework/blob/450de15e79da1f9fb160a8d8eb8ff47eedafbb3e/src/Framework/StorageControl.cxx#L68). I propose taking the `hint_mustKeep` literally.

**Comment by tomeichlersmith** [comment]
Can you elaborate on your proposed solution?

I think the reason this original voting system was implemented was to handle the case where there are votes to drop _and_ votes to keep. I think a natural extension to this is to have a "weight" for a "must" vote that makes it stronger than a "should" vote. This way it can be applied to Drop votes as well as Keep votes. It sounds like you would like this weight to be extremely large so that if there is a single "must" vote, the "should" votes are effectively ignored. Is that a correct interpretation?

**Comment by bryngemark** [comment]
Hi @tomeichlersmith, yes, this is what I'm thinking. If there is a `mustKeep`, then keep the event. Is there ever a `mustDrop`? And does that ever happen beyond the simulation step? Because for sure we should retain the capability to filter out depending on processes.

I'm pretty sure that, since everyone gets to specify which processors to take hints from, and with the way the typical production workflow is laid out there will for instance not be a conflict between a trigger and a veto (typically we keep a tskim, and then run veto skimming if desired). But you could imagine priority ordered as `mustDrop` > 'mustKeep' > `shouldDrop` > `shouldKeep` (and this is based on us typically using vetoes rather than positive selections of events). Triggers should in this setting set `mustKeep` flags, and if needed they could also use `shouldDrop` as a default.

Any smarter solutions are more than welcome though.

**Comment by tomeichlersmith** [comment]
The good news is changing the meaning of the `must*` keywords will not affect our current processors since they all use `should*`.

```
eichl008@spa-cms017 ~/ldmx/ldmx-sw> rg setStorageHint
Framework/include/Framework/EventProcessor.h
160:  void setStorageHint(framework::StorageControlHint hint) {
161:    setStorageHint(hint, "");
170:  void setStorageHint(framework::StorageControlHint hint,

Framework/test/FunctionalCoreTest.cxx
94:    if (res.passesVeto()) setStorageHint(hint_mustKeep);

Framework/python/ldmxcfg.py.in
544:        Some uses of ``setStorageHint`` in processors include a "reason"

Framework/src/Framework/EventProcessor.cxx
33:void EventProcessor::setStorageHint(framework::StorageControlHint hint,

Hcal/src/Hcal/HcalVetoProcessor.cxx
75:    setStorageHint(framework::hint_shouldKeep);
77:    setStorageHint(framework::hint_shouldDrop);

Hcal/src/Hcal/HcalAlignPolarfires.cxx
108:      setStorageHint(framework::hint_shouldKeep);
113:      setStorageHint(framework::hint_shouldDrop);
118:      setStorageHint(framework::hint_shouldDrop);
125:    setStorageHint(framework::hint_shouldDrop);
131:    setStorageHint(framework::hint_shouldDrop);

Hcal/src/Hcal/HcalWABVetoProcessor.cxx
107:    setStorageHint(framework::hint_shouldKeep);
110:    setStorageHint(framework::hint_shouldDrop);

DQM/src/DQM/EcalDigiVerifier.cxx
70:    setStorageHint(framework::hint_shouldKeep);
72:    setStorageHint(framework::hint_shouldDrop);

Ecal/src/Ecal/DNNEcalVetoProcessor.cxx
67:    setStorageHint(framework::hint_shouldKeep);
69:    setStorageHint(framework::hint_shouldDrop);

Ecal/src/Ecal/EcalVetoProcessor.cxx
819:      setStorageHint(framework::hint_shouldKeep);
821:      setStorageHint(framework::hint_shouldDrop);
826:    setStorageHint(framework::hint_shouldKeep);
828:    setStorageHint(framework::hint_shouldDrop);

Recon/src/Recon/Skims/RecoilMissesEcalSkimmer.cxx
55:    setStorageHint(framework::hint_shouldDrop);
57:    setStorageHint(framework::hint_shouldKeep);

Recon/src/Recon/TriggerProcessor.cxx
100:    setStorageHint(framework::hint_shouldKeep);
102:    setStorageHint(framework::hint_shouldDrop);

Recon/src/Recon/SequentialTrigger.cxx
77:    setStorageHint(framework::hint_shouldKeep);
79:    setStorageHint(framework::hint_shouldDrop);
```
