### ISSUE TITLE
enableLogging macro not fully specifying namespace

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/Framework#82]
When using the `enableLogging` macro outside of the `framework` namespace, one can see

```
/Users/einarelen/ldmx/ldmx-sw/Framework/include/Framework/Logger.h:137:11: error: 'logging' does not name a type; did you mean 'long'?
  137 |   mutable logging::logger theLog_{logging::makeLogger(name)};
      |           ^~~~~~~
/Users/einarelen/ldmx/ldmx-sw/Framework/include/Framework/Logger.h:137:11: note: in definition of macro 'enableLogging'
  137 |   mutable logging::logger theLog_{logging::makeLogger(name)};
      |           ^~~~~~~
```

This can be resolved simply by updating the macro to use a fully-specified namespace.

**Comment by tomeichlersmith** [comment]
https://github.com/LDMX-Software/Framework/blob/84e6fdb116bed5dff0604aec077ed641e926814e/include/Framework/Logger.h#L136-L137

**Comment by EinarElen** [comment]
Adding as a reminder here when this is patched, https://github.com/LDMX-Software/SimCore/blob/20d9bcb6d2bad2b99255cf32c1b3f099b26752b0/include/SimCore/KaonPhysics.h#L158-L159 can be patched to use the macro
